FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

COPY . .

WORKDIR "/src/source/VizGurka"
RUN dotnet restore "VizGurka.csproj"
WORKDIR "/src/source/GurkaSpec"
RUN dotnet restore "GurkaSpec.csproj"

WORKDIR "/src/source/VizGurka"
RUN dotnet publish "VizGurka.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
EXPOSE 8080:8080

COPY --from=build /app/publish .
# Set environment variables
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false

ENTRYPOINT ["dotnet", "VizGurka.dll"]
