name: Main - Build and publish docker image

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push-containers:
    runs-on: ubuntu-latest
    env: 
      package-name: specgurka-cli
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3.1.0
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Build and push SpecGurka-image
      uses: docker/build-push-action@v3
      with:
        push: true
        context: ${{env.working-directory}}
        file: source/SpecGurka/dockerfile
        tags: |
          ghcr.io/nonsultant/specgurka/${{env.package-name}}:latest
          ghcr.io/nonsultant/specgurka/${{env.package-name}}:build-${{ github.run_number }}
        labels: |
          org.opencontainers.image.source=https://github.com/${{ github.repository }}