name: SyncGurka CI - Build docker image

on:
  push

jobs:
  ci-build-containers:
    runs-on: ubuntu-latest
    env: 
      package-name: syncgurka-cli
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3.1.0
    # TODO: Run unit tests
    - name: Build SyncGurka-image
      uses: docker/build-push-action@v3
      with:
        context: ${{env.working-directory}}
        file: source/SyncGurka/dockerfile